[package]
name = "storarc-fhe"
version = "0.1.0"
edition = "2021"

[dependencies]
bincode = "1.3.3"
get-size = "0.1.4"
regex = "1.10.6"

tfhe = { version = "0.7.3", features = [ "boolean", "shortint", "integer", "aarch64-unix" ] }
